fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
    archive:
      repo: "puppet/archive"
    file_capability:
      repo: "stm/file_capability"
  symlinks:
    autorestic: "#{source_dir}"
